version: '3'

services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=appuser
      - APP_DB_PASS=appuser
      - APP_DB_NAME=formulary
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./data:/data
    ports:
      - 5432:5432